[core]
reloadable = true
order = 0

[package]
version = "0.1.1"
category = "Simulation"
feature = false
app = false
title = "ROS2 Bridge (semu namespace)"
description = "ROS2 interfaces (semu namespace)"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/semu.robotics.ros2_bridge"
keywords = ["ROS2", "control"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[package.target]
config = ["release"]
platform = ["linux-x86_64"]
python = ["py37", "cp37"]

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ros2_bridge" = {}
"semu.usd.schemas" = {}
"semu.robotics.ros_bridge_ui" = {}

[[python.module]]
name = "semu.robotics.ros2_bridge"

[[python.module]]
name = "semu.robotics.ros2_bridge.tests"

[settings]
exts."semu.robotics.ros2_bridge".nodeName = "SemuRos2Bridge"
exts."semu.robotics.ros2_bridge".eventTimeout = 5.0
exts."semu.robotics.ros2_bridge".setAttributeUsingAsyncio = false

[[native.library]]
path = "bin/libadd_on_msgs__python.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__python.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_introspection_c.so"
