[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "ROS2 Bridge (add-on)"
description = "ROS2 interfaces for add-ons"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/omni.add_on.ros2_bridge"
keywords = ["add-on", "ROS2", "control"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ros2_bridge" = {}
"omni.usd.schema.add_on" = {}
"omni.add_on.ros_bridge_ui" = {}

[[python.module]]
name = "omni.add_on.ros2_bridge"

[[python.module]]
name = "omni.add_on.ros2_bridge.tests"

[settings]
exts."omni.add_on.ros2_bridge".nodeName = "OmniAddOnRos2Bridge"
exts."omni.add_on.ros2_bridge".eventTimeout = 5.0
exts."omni.add_on.ros2_bridge".setAttributeUsingAsyncio = false

[[native.library]]
path = "bin/libadd_on_msgs__python.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libadd_on_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__python.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libcontrol_msgs__rosidl_typesupport_introspection_c.so"
